version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitProjectTestPullProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852/NewGitProjectTestPullProject
  gitUsername: santhu736852
  gitBranch: main
